//
// Generated file, do not edit! Created by nedtool 5.5 from PingPong.msg.
//

#ifndef __INET_PINGPONG_M_H
#define __INET_PINGPONG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

class PingPongPacket;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Enum generated from <tt>PingPong.msg:27</tt> by nedtool.
 * <pre>
 * //
 * // Generic network protocol packet for testing network connectivity.
 * //
 * enum PingPongMessageType
 * {
 *     PING = 0;
 *     PONG = 1;
 * }
 * </pre>
 */
enum PingPongMessageType {
    PING = 0,
    PONG = 1
};

/**
 * Class generated from <tt>PingPong.msg:33</tt> by nedtool.
 * <pre>
 * class PingPongPacket extends FieldsChunk
 * {
 *     PingPongMessageType type; //The type 
 *     int identifier; // identifier to aid in matching Echo replies. May be Zero
 *     int seqNumber; // sequence number to aid in matching Echo replies. May be Zero
 * }
 * </pre>
 */
class PingPongPacket : public ::inet::FieldsChunk
{
  protected:
    inet::PingPongMessageType type = static_cast<inet::PingPongMessageType>(-1);
    int identifier = 0;
    int seqNumber = 0;

  private:
    void copy(const PingPongPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PingPongPacket&);

  public:
    PingPongPacket();
    PingPongPacket(const PingPongPacket& other);
    virtual ~PingPongPacket();
    PingPongPacket& operator=(const PingPongPacket& other);
    virtual PingPongPacket *dup() const override {return new PingPongPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual inet::PingPongMessageType getType() const;
    virtual void setType(inet::PingPongMessageType type);
    virtual int getIdentifier() const;
    virtual void setIdentifier(int identifier);
    virtual int getSeqNumber() const;
    virtual void setSeqNumber(int seqNumber);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PingPongPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PingPongPacket& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_PINGPONG_M_H

